# Use the latest Nginx
FROM nginx:latest

# Copy softy-pink files to Nginx
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf